name = input("Enter your full name: ")
age = input("Enter your age: ")
course = input("Enter your course: ")
section = input("Enter your section: ")
address = input("Enter your address: ")
favorite_food = input("Enter your favorite food: ")

print("===== USER PROFILE =====")
print("Name:", "Cris Jhiliane Abergas" )
print("Age:", "18")
print("Course:", "BSIT")
print("Section:", "BSIT-S10")
print("Address:", "153, Inspector, Santa Rosa, Nueva Ecija, Philippines, 3101")
print("Favorite Food:", "Adobo")